
name: Deploy Pre Prod on Heroku
# on:
#   push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev


jobs:
  deploy:
    name: Deployement-Preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - run: gem install dpl
      - run: dpl --provider=heroku --app=pp-dentiio-front --api-key=${{ secrets.API_KEY_HEROKU }}