
name: Linter React
on: [push]

jobs:
  eslint:
    name: Run EsLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@master
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}