name: CI

on:
  push:
    branches: 
    - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build 
      run: yarn build
      
    - name: Install Dependencies
      run: yarn
      
#    - name: Test
#     run: yarn test --watchAll=false
      
    - name: move build file script
      run: |
        mv ../build/* ../
        
