name: deploy-preprod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Preprod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_PP }}
          username: ${{ secrets.SSH_USER_PP }}
          password: ${{ secrets.SSH_PASSWORD_PP }}
          script: |
            cd /var/www/html/dentiio-app
            sudo git pull origin main
            sudo yarn
            sudo yarn build