#on:
#  push:
#    branches:
#      - dev
#      - master
#  pull_request:
#      types: [opened, synchronize, reopened]
#name: SonarCloud Workflow
#jobs:
#  sonarcloud:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: SonarCloud Test
#      uses: sonarsource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
